BASE_URL = 'https://stellarburgers.nomoreparties.site/api/'
INGREDIENTS_URL = f'{BASE_URL}ingredients'
REGISTER_URL = f'{BASE_URL}auth/register'
LOGIN_URL = f'{BASE_URL}auth/login'
USER_URL = f'{BASE_URL}auth/user'
ORDERS_URL = f'{BASE_URL}orders'